name: Auto Merge Pull Requests

on:
  schedule:
    - cron: "29 18 * * *"  # Runs daily at 11:59 PM IST
  workflow_dispatch:       # Allows manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Auto Approve All Open PRs
        uses: peter-evans/approve-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          approve-all: true

      - name: Auto Merge Pull Requests
        uses: pascalgn/automerge-action@v0.15.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "--auto-merge --merge-method squash"
