name: Auto Merge Pull Requests

on:
  schedule:
    - cron: "29 18 * * *"  # 11:59 PM IST
  workflow_dispatch:  # manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Auto Approve Pull Requests
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto Merge Pull Requests
        uses: pascalgn/automerge-action@v0.15.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "--auto-merge --merge-method squash"
