name: Auto Merge Pull Requests

on:
  schedule:
    - cron: "29 18 * * *"  # 11:59 PM IST = 18:29 UTC
  workflow_dispatch: # Allows manual trigger if needed

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Auto Merge Pull Requests
        uses: pascalgn/automerge-action@v0.15.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "--auto-merge --merge-method squash"
