name: Daily PR Auto-Merge with Points

on:
  schedule:
    - cron: '29 18 * * *'  # 11:59 PM IST
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      statuses: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install PyGithub

      - name: Process PRs and update points
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 <<'EOF'
          import os
          import json
          from datetime import datetime
          from github import Github
          from github.GithubException import GithubException

          # Configuration
          POINTS_PER_PR = 3

          # Initialize
          g = Github(os.environ['GITHUB_TOKEN'])
          repo = g.get_repo(os.environ['GITHUB_REPOSITORY'])

          # Load or create points.json
          try:
              contents = repo.get_contents("points.json")
              points_data = json.loads(contents.decoded_content.decode())
              file_sha = contents.sha
          except:
              points_data = {"users": {}, "history": []}
              file_sha = None

          # Process all open PRs
          for pr in repo.get_pulls(state='open'):
              print(f"\nProcessing PR #{pr.number} by @{pr.user.login}")
              
              try:
                  # Check mergeability first
                  if not pr.mergeable:
                      print(f"PR #{pr.number} not mergeable (mergeable_state: {pr.mergeable_state})")
                      continue
                      
                  # Approve PR
                  pr.create_review(event="APPROVE", body="Auto-approved by workflow")
                  
                  # Merge PR
                  merge_result = pr.merge(merge_method="squash")
                  
                  if merge_result.merged:
                      # Update points
                      username = pr.user.login
                      current_points = points_data["users"].get(username, 0)
                      points_data["users"][username] = current_points + POINTS_PER_PR
                      
                      points_data["history"].append({
                          "username": username,
                          "points": POINTS_PER_PR,
                          "pr_number": pr.number,
                          "date": datetime.now().isoformat(),
                          "reason": "PR merged"
                      })
                      print(f"Successfully merged PR #{pr.number} and added {POINTS_PER_PR} points to @{username}")
                      
              except GithubException as e:
                  print(f"Failed to process PR #{pr.number}: {str(e)}")
                  continue

          # Save updated points
          try:
              updated_content = json.dumps(points_data, indent=2)
              if file_sha:
                  repo.update_file(
                      path="points.json",
                      message=f"Update points: {len(points_data['history'])} PRs processed",
                      content=updated_content,
                      sha=file_sha
                  )
              else:
                  repo.create_file(
                      path="points.json",
                      message="Initialize points tracking",
                      content=updated_content
                  )
              print("Successfully updated points.json")
          except Exception as e:
              print(f"Failed to update points.json: {str(e)}")
          EOF
