name: Auto Approve and Merge PRs with Points

on:
  schedule:
    - cron: '29 18 * * *'  # 11:59 PM IST
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Git Identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Install Python dependencies
        run: pip install requests

      - name: Initialize points.json
        run: |
          if [ ! -f "points.json" ]; then
            echo '{"users":{},"history":[]}' > points.json
            git add points.json
            git commit -m "Initialize points tracking"
            git pull --rebase origin main
            git push origin main
          fi

      - name: Process PRs and Update Points
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          python3 <<EOF
          [Insert the full Python code from previous example here]
          EOF

          git add points.json
          git commit -m "Update points after PR merges" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main

      - name: Verify points file
        run: |
          echo "Points file content:"
          cat points.json
          echo -e "\n\nAccess at:"
          echo "https://raw.githubusercontent.com/${{ github.repository }}/main/points.json"
