name: Update Points and Merge PRs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  merge-and-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install PyGithub python-dateutil

    - name: Merge PRs and update points
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        import json
        import os
        import sys
        from github import Github
        from datetime import datetime, timezone
        from dateutil import parser

        # Debugging info
        print("Python version:", sys.version)
        print("Current directory:", os.getcwd())
        print("Repository contents:", os.listdir('.'))

        try:
            with open('points.json', 'r') as f:
                data = json.load(f)
                print("Current data loaded successfully")
        except Exception as e:
            print(f"Error loading JSON file: {str(e)}")
            sys.exit(1)

        try:
            g = Github(os.getenv('GITHUB_TOKEN'))
            repo = g.get_repo(os.getenv('GITHUB_REPOSITORY'))
            print(f"Connected to {repo.full_name}")
        except Exception as e:
            print(f"Error connecting to GitHub: {str(e)}")
            sys.exit(1)

        # First pull any remote changes
        os.system('git pull origin main')

        users_points_today = {}
        today = datetime.now(timezone.utc).date()
        merged_users = set()

        # Check existing users' last points date
        for username in data.get('users', {}):
            if 'last_points_date' in data['users'][username]:
                last_date = parser.parse(data['users'][username]['last_points_date']).date()
                if last_date == today:
                    users_points_today[username] = True
                    print(f"User {username} already got points today")

        # Process open PRs
        open_prs = list(repo.get_pulls(state='open'))
        print(f"Found {len(open_prs)} open PRs")

        for pr in open_prs:
            username = pr.user.login
            print(f"\nProcessing PR #{pr.number} from {username}")

            if username in users_points_today:
                print(f"Skipping {username} - already received points today")
                continue

            try:
                if pr.mergeable:
                    print(f"Merging PR #{pr.number}")
                    pr.merge(merge_method='merge')
                    merged_users.add(username)
                    users_points_today[username] = True
                    print(f"Successfully merged PR #{pr.number}")
                else:
                    print(f"PR #{pr.number} not mergeable (state: {pr.mergeable_state})")
            except Exception as e:
                print(f"Error merging PR #{pr.number}: {str(e)}")

        # Update points
        if merged_users:
            current_date = datetime.now(timezone.utc).isoformat()
            print(f"\nUpdating points for {len(merged_users)} users")
            
            for username in merged_users:
                if username in data['users']:
                    data['users'][username]['points'] += 3
                    data['users'][username]['last_points_date'] = current_date
                    print(f"Added 3 points to {username} (Total: {data['users'][username]['points']})")
                else:
                    data['users'][username] = {
                        "points": 3,
                        "social_media_points": 0,
                        "last_points_date": current_date
                    }
                    print(f"Created new entry for {username}")

            # Save changes
            with open('points.json', 'w') as f:
                json.dump(data, f, indent=2)

            # Commit and push
            os.system('git config --global user.name "GitHub Actions"')
            os.system('git config --global user.email "actions@github.com"')
            os.system('git add points.json')
            os.system('git commit -m "Automated points update for merged PRs"')
            
            # Handle push with retry
            max_retries = 3
            for attempt in range(max_retries):
                print(f"Push attempt {attempt + 1}/{max_retries}")
                result = os.system('git pull --rebase origin main && git push origin main')
                if result == 0:
                    print("Push successful")
                    break
                print(f"Push failed, retrying...")
            else:
                print("Failed to push after multiple attempts")
                sys.exit(1)
        else:
            print("No users eligible for points update")
      shell: python